name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -t m2etu@51.89.7.73 << 'EOF'
            cd /home/m2etu/civicalert-api/
            if [ -d .git ]; then
              git pull
            else
              echo "Not a git repository"
              exit 1
            fi
            docker-compose up --build -d slim
          EOF
